//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pilote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pilote()
        {
            this.Vols = new HashSet<Vol>();
        }
    
        public int Num_pil { get; set; }
        [Required]
        [MaxLength(10)]
        public string Nom_pil { get; set; }
        [Required]
        [MaxLength(10)]
        public string Prenom_pil { get; set; }
        [Required]
        [MaxLength(10)]
        public string Ville_Domicile { get; set; }
        [Required]
        [Phone]
        public Nullable<int> Num_tel { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public Nullable<int> Salaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vol> Vols { get; set; }
    }
}
