//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vol
    {
        public int Num_Vol { get; set; }
        public Nullable<int> Num_Pil { get; set; }
        public Nullable<int> Num_Av { get; set; }
        [Required]
        [MaxLength(10)]
        public string Ville_Depart { get; set; }
        [Required]
        [MaxLength(10)]
        public string Ville_Arrivee { get; set; }
        [Required]
        public Nullable<System.DateTime> Date_depart { get; set; }
        [Required]
        public Nullable<System.DateTime> Date_arrivee { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Pilote Pilote { get; set; }
    }
}
